service: hubspot-sync-props

provider:
  name: aws
  
resources:
  Resources:
    hubspotUserRules:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HubspotUserRules
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: user.id
            AttributeType: S
          - AttributeName: app.id
            AttributeType: S
        KeySchema:
          - AttributeName: user.id
            KeyType: HASH
          - AttributeName: app.id
            KeyType: RANGE

    hubspotTokens:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: HubspotAppTokens
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: user.id
            AttributeType: S
          - AttributeName: app.id
            AttributeType: S
        KeySchema:
          - AttributeName: user.id
            KeyType: HASH
          - AttributeName: app.id
            KeyType: RANGE
